## syntax=docker/dockerfile:1

## python 3.9x needed due to an error I didn't log
FROM python:3.9

## the tutorials include these; todo- figure out what they do
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

## set shell to bash instead of sh
# RUN chsh -s /bin/bash  # doesn't work; hmm...

## who doesn't love a "stuff" directory!  :)
WORKDIR /sr_project_stuff/code
RUN mkdir /sr_project_stuff/logs
RUN mkdir /sr_project_stuff/DBs

## set up the python environment
COPY ./config/requirements_local.txt /sr_project_stuff/code/
RUN pip install -r ./requirements_local.txt  

## set up SSH access per <https://dev.to/alvarocavalcanti/setting-up-a-python-remote-interpreter-using-docker-1i24>
RUN apt-get update \
 && apt-get install -y openssh-server \
 && mkdir /var/run/sshd \
 && echo 'root:password' | chpasswd \
 && sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
